In [38]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [39]:
## test sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good Developer',
    'Understand the meaning of words',
    'your videos are good'
]

In [40]:
voc_size = 10000

In [41]:
one_hot_rep = [one_hot(words, voc_size) for words in sent]
one_hot_rep

[[4501, 5779, 5892, 2812],
 [4501, 5779, 5892, 3300],
 [4501, 3263, 5892, 6927],
 [4478, 2346, 9428, 1692, 5304],
 [4478, 2346, 9428, 1692, 6224],
 [9846, 4501, 3233, 5892, 3575],
 [3328, 7963, 6238, 1692]]

In [42]:
max_sent_length = 8
embedded_doc = pad_sequences(one_hot_rep, max_sent_length, padding = 'pre')
embedded_doc

array([[   0,    0,    0,    0, 4501, 5779, 5892, 2812],
       [   0,    0,    0,    0, 4501, 5779, 5892, 3300],
       [   0,    0,    0,    0, 4501, 3263, 5892, 6927],
       [   0,    0,    0, 4478, 2346, 9428, 1692, 5304],
       [   0,    0,    0, 4478, 2346, 9428, 1692, 6224],
       [   0,    0,    0, 9846, 4501, 3233, 5892, 3575],
       [   0,    0,    0,    0, 3328, 7963, 6238, 1692]])

In [12]:
opt = tf.keras.optimizers.Adam(learning_rate=0.1)

In [43]:
word_dim = 10

In [44]:
model = Sequential()
embedding_layer = Embedding(input_dim=voc_size, output_dim=word_dim)
model.add(embedding_layer)
embedding_layer.build((None, sent_length))

In [45]:
model.summary()

Model: "sequential_8"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_8 (Embedding)              │ (None, 8, 10)               │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [46]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 446ms/step


array([[[ 0.03004456, -0.00408792, -0.04790777, -0.0473907 ,
         -0.04843929, -0.00966102, -0.00485513,  0.0338115 ,
         -0.04614064,  0.02610154],
        [ 0.03004456, -0.00408792, -0.04790777, -0.0473907 ,
         -0.04843929, -0.00966102, -0.00485513,  0.0338115 ,
         -0.04614064,  0.02610154],
        [ 0.03004456, -0.00408792, -0.04790777, -0.0473907 ,
         -0.04843929, -0.00966102, -0.00485513,  0.0338115 ,
         -0.04614064,  0.02610154],
        [ 0.03004456, -0.00408792, -0.04790777, -0.0473907 ,
         -0.04843929, -0.00966102, -0.00485513,  0.0338115 ,
         -0.04614064,  0.02610154],
        [ 0.00850974,  0.01504571,  0.01397857, -0.04893384,
          0.03702382, -0.03282566, -0.03311589, -0.02649988,
         -0.02301209,  0.01830358],
        [ 0.02692709,  0.00456178, -0.02060453,  0.04791978,
          0.00146275, -0.01279926,  0.04570771,  0.04541358,
         -0.03051368,  0.02753944],
        [-0.03422552, -0.0104141 , -0.02939867,  0.0

In [47]:
embedded_doc[0]

array([   0,    0,    0,    0, 4501, 5779, 5892, 2812])

In [48]:
single_input = np.expand_dims(embedded_doc[0], axis=0)

In [49]:
model.predict(single_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 141ms/step


array([[[ 0.03004456, -0.00408792, -0.04790777, -0.0473907 ,
         -0.04843929, -0.00966102, -0.00485513,  0.0338115 ,
         -0.04614064,  0.02610154],
        [ 0.03004456, -0.00408792, -0.04790777, -0.0473907 ,
         -0.04843929, -0.00966102, -0.00485513,  0.0338115 ,
         -0.04614064,  0.02610154],
        [ 0.03004456, -0.00408792, -0.04790777, -0.0473907 ,
         -0.04843929, -0.00966102, -0.00485513,  0.0338115 ,
         -0.04614064,  0.02610154],
        [ 0.03004456, -0.00408792, -0.04790777, -0.0473907 ,
         -0.04843929, -0.00966102, -0.00485513,  0.0338115 ,
         -0.04614064,  0.02610154],
        [ 0.00850974,  0.01504571,  0.01397857, -0.04893384,
          0.03702382, -0.03282566, -0.03311589, -0.02649988,
         -0.02301209,  0.01830358],
        [ 0.02692709,  0.00456178, -0.02060453,  0.04791978,
          0.00146275, -0.01279926,  0.04570771,  0.04541358,
         -0.03051368,  0.02753944],
        [-0.03422552, -0.0104141 , -0.02939867,  0.0