In [10]:
import tensorflow as tf
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [4]:
## test sentences
sent = [
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'I am a good boy',
    'I am a good Developer',
    'Understand the meaning of words',
    'your videos are good'
]

In [5]:
voc_size = 10000

In [6]:
one_hot_rep = [one_hot(words, voc_size) for words in sent]
one_hot_rep

[[4501, 5779, 5892, 2812],
 [4501, 5779, 5892, 3300],
 [4501, 3263, 5892, 6927],
 [4478, 2346, 9428, 1692, 5304],
 [4478, 2346, 9428, 1692, 6224],
 [9846, 4501, 3233, 5892, 3575],
 [3328, 7963, 6238, 1692]]

In [20]:
sent_length = 8
embedded_doc = pad_sequences(one_hot_rep, sent_length, padding = 'pre')
embedded_doc

array([[   0,    0,    0,    0, 4501, 5779, 5892, 2812],
       [   0,    0,    0,    0, 4501, 5779, 5892, 3300],
       [   0,    0,    0,    0, 4501, 3263, 5892, 6927],
       [   0,    0,    0, 4478, 2346, 9428, 1692, 5304],
       [   0,    0,    0, 4478, 2346, 9428, 1692, 6224],
       [   0,    0,    0, 9846, 4501, 3233, 5892, 3575],
       [   0,    0,    0,    0, 3328, 7963, 6238, 1692]])

In [12]:
opt = tf.keras.optimizers.Adam(learning_rate=0.1)

In [26]:
dim = 10

In [27]:
model = Sequential()
embedding_layer = Embedding(input_dim=voc_size, output_dim=dim)
model.add(embedding_layer)
embedding_layer.build((None, sent_length))

In [28]:
model.summary()

Model: "sequential_7"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_7 (Embedding)              │ (None, 8, 10)               │         100,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [29]:
model.predict(embedded_doc)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 214ms/step


array([[[-0.02550524, -0.03034973, -0.01113306, -0.02560756,
         -0.03275429, -0.04236194, -0.03500264,  0.01230841,
          0.01522477, -0.04113315],
        [-0.02550524, -0.03034973, -0.01113306, -0.02560756,
         -0.03275429, -0.04236194, -0.03500264,  0.01230841,
          0.01522477, -0.04113315],
        [-0.02550524, -0.03034973, -0.01113306, -0.02560756,
         -0.03275429, -0.04236194, -0.03500264,  0.01230841,
          0.01522477, -0.04113315],
        [-0.02550524, -0.03034973, -0.01113306, -0.02560756,
         -0.03275429, -0.04236194, -0.03500264,  0.01230841,
          0.01522477, -0.04113315],
        [-0.02631654, -0.01876124, -0.01110718, -0.00457488,
          0.02497262, -0.01369584, -0.00361625,  0.04276669,
          0.0121255 , -0.03842522],
        [-0.00965584,  0.01593644,  0.03313876, -0.04432476,
          0.00220167,  0.04390598, -0.04697065, -0.03633798,
         -0.04450004,  0.03379237],
        [-0.02556851, -0.00769719, -0.0451273 , -0.0

In [30]:
embedded_doc[0]

array([   0,    0,    0,    0, 4501, 5779, 5892, 2812])

In [36]:
single_input = np.expand_dims(embedded_doc[0], axis=0)

In [37]:
model.predict(single_input)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step


array([[[-0.02550524, -0.03034973, -0.01113306, -0.02560756,
         -0.03275429, -0.04236194, -0.03500264,  0.01230841,
          0.01522477, -0.04113315],
        [-0.02550524, -0.03034973, -0.01113306, -0.02560756,
         -0.03275429, -0.04236194, -0.03500264,  0.01230841,
          0.01522477, -0.04113315],
        [-0.02550524, -0.03034973, -0.01113306, -0.02560756,
         -0.03275429, -0.04236194, -0.03500264,  0.01230841,
          0.01522477, -0.04113315],
        [-0.02550524, -0.03034973, -0.01113306, -0.02560756,
         -0.03275429, -0.04236194, -0.03500264,  0.01230841,
          0.01522477, -0.04113315],
        [-0.02631654, -0.01876124, -0.01110718, -0.00457488,
          0.02497262, -0.01369584, -0.00361625,  0.04276669,
          0.0121255 , -0.03842522],
        [-0.00965584,  0.01593644,  0.03313876, -0.04432476,
          0.00220167,  0.04390598, -0.04697065, -0.03633798,
         -0.04450004,  0.03379237],
        [-0.02556851, -0.00769719, -0.0451273 , -0.0